"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronDown, CircleDollarSign, Clock3, LayoutDashboard, Menu, MoreHorizontal, Plus, Scissors, Search, Settings, UserRound, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { services, money } from "../data";

type Appointment={id:string;clientName:string;phone:string;email?:string|null;notes?:string|null;serviceId:string;barberId:string;date:string;time:string;price:number;status:string;startAt?:number};
const statusMap:Record<string,{label:string,style:string}>={pending:{label:"Pendiente",style:"bg-amber-400/15 text-amber-300"},confirmed:{label:"Confirmada",style:"bg-blue-400/15 text-blue-300"},arrived:{label:"Llegó",style:"bg-violet-400/15 text-violet-300"},in_progress:{label:"En silla",style:"bg-[#e84c3d]/15 text-[#e84c3d]"},completed:{label:"Completada",style:"bg-emerald-400/15 text-emerald-300"},cancelled:{label:"Cancelada",style:"bg-red-400/15 text-red-300"},no_show:{label:"No llegó",style:"bg-zinc-400/15 text-zinc-300"}};
export function AdminDashboard({userName}:{userName:string}){
 const [appointments,setAppointments]=useState<Appointment[]>([]);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState(false);const [sidebar,setSidebar]=useState(false);const [addOpen,setAddOpen]=useState(false);const [selected,setSelected]=useState<Appointment|null>(null);
 useEffect(()=>{fetch("/api/admin/appointments").then(async r=>{if(r.status===401){window.location.assign("/admin/login");return null}if(!r.ok)throw new Error("load");return r.json()}).then(d=>{if(d)setAppointments(d.appointments??[])}).catch(()=>setLoadError(true)).finally(()=>setLoading(false))},[]);
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota"}).format(new Date());
 const todayAppointments=useMemo(()=>appointments.filter(a=>a.date===today),[appointments,today]);
 const revenue=useMemo(()=>todayAppointments.filter(a=>a.status!=="cancelled").reduce((n,a)=>n+a.price,0),[todayAppointments]);
 const nextAppointment=appointments.find(a=>!["completed","cancelled","no_show"].includes(a.status));
 const updateStatus=async(id:string,status:string)=>{setAppointments(items=>items.map(a=>a.id===id?{...a,status}:a));await fetch("/api/admin/appointments",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})})};
 const signOut=async()=>{await fetch("/api/admin/session",{method:"DELETE"});window.location.assign("/admin/login")};
 return <main className="min-h-screen bg-[#0b0b0a] text-[#f4f1e8]">
  <aside className={`fixed inset-y-0 left-0 z-40 w-72 border-r border-white/10 bg-[#11110f] p-5 transition lg:translate-x-0 ${sidebar?"translate-x-0":"-translate-x-full"}`}><button onClick={()=>setSidebar(false)} className="absolute right-4 top-4 lg:hidden"><X/></button><a href="/" className="mb-10 flex items-center gap-3"><img src="/jota-eme-logo.jpg" alt="Jota Eme" className="h-12 w-12 rounded-full bg-white object-cover"/><span><b className="display block text-xl">Jota Eme</b><small className="text-[10px] font-bold tracking-[.18em] text-white/35">STUDIO OS</small></span></a><p className="eyebrow mb-3 text-white/30">OPERACIONES</p><nav className="space-y-1">{[[LayoutDashboard,"Hoy"],[CalendarDays,"Calendario"],[Users,"Clientes"],[Scissors,"Servicios"],[UserRound,"Equipo"],[Settings,"Configuración"]].map(([Icon,label],i)=><button key={String(label)} className={`flex h-12 w-full items-center gap-3 px-4 text-left text-sm font-semibold ${i===0?"bg-[#e84c3d] text-black":"text-white/55 hover:bg-white/[.05] hover:text-white"}`}><Icon size={18}/>{String(label)}</button>)}</nav><div className="absolute inset-x-5 bottom-5 border-t border-white/10 pt-5"><p className="truncate text-sm font-semibold">{userName}</p><button onClick={signOut} className="mt-1 text-xs text-white/35 hover:text-white">Cerrar sesión</button></div></aside>
  <div className="lg:pl-72"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-white/10 bg-[#0b0b0a]/90 px-4 backdrop-blur-xl sm:px-7"><div className="flex items-center gap-3"><button onClick={()=>setSidebar(true)} className="lg:hidden"><Menu/></button><div><h1 className="text-xl font-black">Hoy en Jota Eme</h1><p className="text-xs capitalize text-white/35">Domingo, 13 de septiembre · Cartagena</p></div></div><div className="flex items-center gap-2"><button className="hidden h-10 items-center gap-2 border border-white/10 px-4 text-sm text-white/55 sm:flex"><Search size={16}/> Buscar</button><Button onClick={()=>setAddOpen(true)} className="h-10 rounded-none font-black"><Plus/> <span className="hidden sm:inline">NUEVA CITA</span></Button></div></header>
   <div className="mx-auto max-w-[1500px] p-4 sm:p-7">
    {loadError&&<div className="mb-4 border border-red-400/25 bg-red-400/10 p-4 text-sm text-red-100">No pudimos cargar la agenda. Actualiza la página para volver a intentarlo.</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[CalendarDays,"Citas hoy",loading?"—":todayAppointments.length,"Agenda real"],[Clock3,"Próxima cita",nextAppointment?.time??"—",nextAppointment?`${nextAppointment.clientName} · ${nextAppointment.date}`:"Sin citas próximas"],[CircleDollarSign,"Ingresos estimados",money(revenue),"Hoy"],[Users,"Próximas reservas",appointments.length,"Desde hoy"]].map(([Icon,label,value,note])=><article key={String(label)} className="border border-white/10 bg-[#141412] p-5"><div className="flex justify-between"><span className="text-sm text-white/40">{String(label)}</span><Icon size={19} className="text-[#e84c3d]"/></div><b className="mt-5 block text-3xl">{String(value)}</b><small className="mt-2 block text-white/30">{String(note)}</small></article>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_330px]"><div className="border border-white/10 bg-[#141412]"><div className="flex flex-col gap-4 border-b border-white/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">Agenda del día</h2><p className="mt-1 text-sm text-white/35">{todayAppointments.length} citas para hoy</p></div><Tabs defaultValue="day"><TabsList className="bg-white/[.05]"><TabsTrigger value="day">Día</TabsTrigger><TabsTrigger value="week">Semana</TabsTrigger><TabsTrigger value="month">Mes</TabsTrigger></TabsList></Tabs></div><div className="grid grid-cols-[72px_1fr] sm:grid-cols-[92px_1fr_1fr]"><div className="border-r border-white/10 p-3 text-xs text-white/25">HORA</div><div className="border-r border-white/10 p-3 text-xs font-bold text-white/45">CHEO</div><div className="hidden p-3 text-xs font-bold text-white/45 sm:block">ALEJANDRO</div>{["9:15 AM","10:00 AM","11:30 AM","12:30 PM","2:15 PM","4:30 PM","6:45 PM"].map(time=>{const rows=todayAppointments.filter(a=>a.time===time);return <div key={time} className="contents"><div className="min-h-28 border-r border-t border-white/10 p-3 text-xs text-white/35">{time}</div>{["cheo","alejandro"].map((barber,i)=>{const a=rows.find(x=>x.barberId===barber);return <div key={barber} className={`${i===1?"hidden sm:block":""} min-h-28 border-r border-t border-white/10 p-2`}>{a?<button onClick={()=>setSelected(a)} className={`h-full w-full border-l-2 p-3 text-left ${barber==="cheo"?"border-[#e84c3d] bg-[#e84c3d]/[.07]":"border-blue-400 bg-blue-400/[.07]"}`}><b className="block text-sm">{a.clientName}</b><span className="mt-1 block text-xs text-white/40">{services.find(s=>s.id===a.serviceId)?.es}</span><span className={`mt-3 inline-block px-2 py-1 text-[10px] font-bold ${statusMap[a.status]?.style}`}>{statusMap[a.status]?.label}</span></button>:<button onClick={()=>setAddOpen(true)} className="h-full w-full border border-dashed border-white/10 text-xs text-white/20 hover:border-[#e84c3d]/50 hover:text-[#e84c3d]">+ DISPONIBLE</button>}</div>})}</div>})}</div></div>
     <aside className="space-y-5"><div className="border border-white/10 bg-[#141412] p-5"><div className="flex items-center justify-between"><h2 className="font-black">Siguiente</h2><span className="text-xs text-[#e84c3d]">PRÓXIMA</span></div>{nextAppointment?<><button onClick={()=>setSelected(nextAppointment)} className="mt-5 flex w-full items-center gap-3 text-left"><div className="grid h-12 w-12 place-items-center rounded-full bg-[#e84c3d] font-black text-black">{nextAppointment.clientName.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><b>{nextAppointment.clientName}</b><small className="block text-white/35">{services.find(s=>s.id===nextAppointment.serviceId)?.es} · {nextAppointment.barberId}</small><small className="block text-white/35">{nextAppointment.date} · {nextAppointment.time}</small></div></button><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>updateStatus(nextAppointment.id,"arrived")} className="h-10 bg-[#e84c3d] text-xs font-black text-black">MARCAR LLEGÓ</button><a href={`https://wa.me/${nextAppointment.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" className="grid h-10 place-items-center border border-white/10 text-xs font-bold">WHATSAPP</a></div></>:<p className="mt-5 text-sm text-white/40">No hay reservas próximas.</p>}</div><div className="border border-white/10 bg-[#141412] p-5"><h2 className="font-black">Acciones rápidas</h2><div className="mt-4 space-y-2"><button onClick={()=>setAddOpen(true)} className="flex h-11 w-full items-center gap-3 border border-white/10 px-4 text-sm hover:border-[#e84c3d]"><Plus size={17}/> Agregar walk-in</button><button className="flex h-11 w-full items-center gap-3 border border-white/10 px-4 text-sm hover:border-[#e84c3d]"><Clock3 size={17}/> Bloquear tiempo</button><button className="flex h-11 w-full items-center gap-3 border border-white/10 px-4 text-sm hover:border-[#e84c3d]"><Users size={17}/> Ver lista de espera</button></div></div></aside>
    </section>
   </div>
  </div>
  <Dialog open={!!selected} onOpenChange={()=>setSelected(null)}><DialogContent className="border-white/10 bg-[#151513] text-white"><DialogHeader><DialogTitle>{selected?.clientName}</DialogTitle></DialogHeader>{selected&&<div><div className="grid grid-cols-2 gap-3 text-sm"><div className="border border-white/10 p-3"><small className="text-white/35">SERVICIO</small><b className="mt-1 block">{services.find(s=>s.id===selected.serviceId)?.es}</b></div><div className="border border-white/10 p-3"><small className="text-white/35">FECHA Y HORA</small><b className="mt-1 block">{selected.date} · {selected.time}</b></div><div className="border border-white/10 p-3"><small className="text-white/35">WHATSAPP</small><a href={`https://wa.me/${selected.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" className="mt-1 block font-bold text-[#e84c3d]">{selected.phone}</a></div><div className="border border-white/10 p-3"><small className="text-white/35">BARBERO</small><b className="mt-1 block capitalize">{selected.barberId}</b></div></div>{selected.notes&&<p className="mt-3 border border-white/10 p-3 text-sm text-white/60">{selected.notes}</p>}<p className="eyebrow mb-3 mt-6 text-white/35">ACTUALIZAR ESTADO</p><div className="grid grid-cols-2 gap-2">{["arrived","in_progress","completed","no_show"].map(s=><button key={s} onClick={()=>{updateStatus(selected.id,s);setSelected(null)}} className="h-11 border border-white/10 text-sm font-semibold hover:border-[#e84c3d]">{statusMap[s].label}</button>)}</div></div>}</DialogContent></Dialog>
  <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="border-white/10 bg-[#151513] text-white"><DialogHeader><DialogTitle>Nueva cita / Walk-in</DialogTitle></DialogHeader><div className="grid gap-3"><Input placeholder="Nombre del cliente" className="h-12 rounded-none border-white/10"/><Input placeholder="WhatsApp" className="h-12 rounded-none border-white/10"/><select className="h-12 border border-white/10 bg-transparent px-3"><option className="bg-black">Seleccionar servicio</option>{services.map(s=><option className="bg-black" key={s.id}>{s.es} · {s.minutes} min</option>)}</select><select className="h-12 border border-white/10 bg-transparent px-3"><option className="bg-black">Cheo Barbero</option><option className="bg-black">Alejandro Barbero</option></select><Button onClick={()=>setAddOpen(false)} className="mt-2 h-12 rounded-none"><Check/> GUARDAR CITA</Button></div></DialogContent></Dialog>
 </main>
}
