"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarPlus, Check, MapPin, Phone, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { money, services, barbers } from "@/app/data";

type Booking={clientName:string;serviceId:string;barberId:string;date:string;time:string;status:string;price:number};

export function BookingManager({token}:{token:string}){
  const [booking,setBooking]=useState<Booking|null>(null);
  const [error,setError]=useState(false);
  useEffect(()=>{void fetch(`/api/booking/${token}`).then(async response=>{if(!response.ok)throw new Error("not found");return await response.json() as Booking}).then(setBooking).catch(()=>setError(true))},[token]);
  const cancel=async()=>{if(!confirm("¿Seguro que deseas cancelar esta cita?"))return;const response=await fetch(`/api/booking/${token}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"cancel"})});if(response.ok)setBooking(current=>current?{...current,status:"cancelled"}:current)};
  const addToCalendar=()=>{if(!booking)return;const start=new Date(`${booking.date}T${to24(booking.time)}:00-05:00`);const end=new Date(start.getTime()+60*60*1000);const stamp=(date:Date)=>date.toISOString().replace(/[-:]/g,"").replace(".000","");const service=services.find(item=>item.id===booking.serviceId)?.es??"Cita Jota Eme";const content=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Jota Eme//Studio OS//ES","BEGIN:VEVENT",`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,`SUMMARY:${service} - Jota Eme`,"LOCATION:Av. San Martín, Edificio San Martín, Local 7, Cartagena","END:VEVENT","END:VCALENDAR"].join("\r\n");const url=URL.createObjectURL(new Blob([content],{type:"text/calendar"}));const link=document.createElement("a");link.href=url;link.download="jota-eme-cita.ics";link.click();URL.revokeObjectURL(url)};
  return <main className="grid min-h-screen place-items-center bg-[#0b0b0a] px-5 py-16 text-[#f3f0e8]"><div className="w-full max-w-xl"><Link href="/" className="mb-7 flex items-center gap-2 text-sm text-white/45"><ArrowLeft size={17}/> Jota Eme</Link>{!booking&&!error?<div className="h-80 animate-pulse bg-white/[.05]"/>:error?<div className="border border-white/10 p-8 text-center"><X className="mx-auto text-red-400"/><h1 className="mt-4 text-2xl font-black">No encontramos esta reserva</h1><p className="mt-2 text-white/45">Revisa el enlace o escríbenos por WhatsApp.</p></div>:booking&&<article className="border border-white/10 bg-[#141412]"><div className="bg-[#e84c3d] p-6 text-black"><Check/><p className="eyebrow mt-5">{booking.status==="cancelled"?"CITA CANCELADA":"RESERVA CONFIRMADA"}</p><h1 className="display mt-2 text-5xl">{booking.clientName}</h1></div><div className="p-6 sm:p-8"><h2 className="text-2xl font-black">{services.find(s=>s.id===booking.serviceId)?.es}</h2><p className="mt-2 text-white/45">con {barbers.find(b=>b.id===booking.barberId)?.name}</p><div className="my-7 grid grid-cols-2 gap-3"><div className="border border-white/10 p-4"><small className="text-white/35">FECHA</small><b className="mt-1 block">{booking.date}</b></div><div className="border border-white/10 p-4"><small className="text-white/35">HORA</small><b className="mt-1 block">{booking.time}</b></div></div><div className="flex justify-between border-y border-white/10 py-4"><span>Total</span><b className="text-[#e84c3d]">{money(booking.price)}</b></div><div className="mt-6 grid gap-2 sm:grid-cols-2"><a target="_blank" rel="noreferrer" href="https://maps.google.com/?q=Av.+San+Martín+Edificio+San+Martín+Local+7+Cartagena" className="flex h-12 items-center justify-center gap-2 border border-white/10 text-sm font-bold"><MapPin size={17}/> CÓMO LLEGAR</a><a href="https://wa.me/573214692733" className="flex h-12 items-center justify-center gap-2 border border-white/10 text-sm font-bold"><Phone size={17}/> WHATSAPP</a><button onClick={addToCalendar} className="flex h-12 items-center justify-center gap-2 border border-white/10 text-sm font-bold"><CalendarPlus size={17}/> AÑADIR AL CALENDARIO</button>{booking.status!=="cancelled"&&<Button onClick={cancel} variant="outline" className="h-12 rounded-none border-red-400/30 text-sm font-bold text-red-300">CANCELAR CITA</Button>}</div></div></article>}</div></main>;
}

function to24(value:string){const match=value.match(/(\d+):(\d+)\s*(AM|PM)/i);if(!match)return value;let hour=Number(match[1]);if(match[3].toUpperCase()==="PM"&&hour!==12)hour+=12;if(match[3].toUpperCase()==="AM"&&hour===12)hour=0;return `${String(hour).padStart(2,"0")}:${match[2]}`}
