"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, AtSign, CalendarDays, Check, ChevronLeft, Clock3, MapPin, Menu, Phone, Scissors, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { barbers, money, services } from "./data";

import { SilentVideo } from "@/components/silent-video";
import { portfolio, studioMedia } from "./media";
const Instagram=AtSign;
const slots=["9:15 AM","10:00 AM","11:30 AM","2:15 PM","4:30 PM","6:45 PM"];


export function HomeExperience(){
  const [lang,setLang]=useState<"es"|"en">("es");
  const [bookingOpen,setBookingOpen]=useState(false);
  const [selectedService,setSelectedService]=useState("haircut");
  const [menuOpen,setMenuOpen]=useState(false);
  const t=(es:string,en:string)=>lang==="es"?es:en;
  const openBooking=(service="haircut")=>{setSelectedService(service);setBookingOpen(true)};

  useEffect(()=>{
    const requested=new URLSearchParams(window.location.search).get("book");
    if(requested&&services.some(s=>s.id===requested))queueMicrotask(()=>openBooking(requested));
    const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    void Promise.resolve(context.registerTool({name:"start_jota_eme_booking",title:"Start a Jota Eme booking",description:"Open the Jota Eme appointment flow with an optional service selected.",inputSchema:{type:"object",properties:{serviceId:{type:"string",enum:services.map(s=>s.id)}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{const serviceId=typeof input==="object"&&input&&"serviceId" in input?String((input as {serviceId:string}).serviceId):"haircut";openBooking(services.some(s=>s.id===serviceId)?serviceId:"haircut");return{opened:true,serviceId}}},{signal:lifecycle.signal})).catch(()=>{});
    return()=>lifecycle.abort();
  },[]);

  return <main className="min-h-screen overflow-hidden bg-[#0a0a09] text-[#f3f0e8]">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#0a0a09]/88 backdrop-blur-xl">
      <div className="mx-auto flex h-[72px] max-w-[1500px] items-center justify-between px-5 lg:px-10">
        <Link href="#inicio" aria-label="Jota Eme inicio" className="flex items-center gap-3">
          <img src="/jota-eme-logo.jpg" alt="" className="h-11 w-11 rounded-full bg-white object-cover"/>
          <span className="leading-none"><b className="display block text-xl tracking-tight">Jota Eme</b><small className="mt-1 block text-[10px] font-bold tracking-[.22em] text-white/45">BARBER STUDIO · EST. 2021</small></span>
        </Link>
        <nav className="hidden items-center gap-7 text-sm font-semibold lg:flex">
          <a href="#servicios" className="hover:text-[#e84c3d]">{t("Servicios","Services")}</a><a href="#barberos" className="hover:text-[#e84c3d]">{t("Barberos","Barbers")}</a><a href="#trabajo" className="hover:text-[#e84c3d]">{t("Cortes","Cuts")}</a><a href="#vip" className="hover:text-[#e84c3d]">VIP</a><a href="#estudio" className="hover:text-[#e84c3d]">{t("El estudio","Studio")}</a>
        </nav>
        <div className="flex items-center gap-2">
          <button onClick={()=>setLang(lang==="es"?"en":"es")} className="h-10 min-w-12 rounded-full border border-white/15 px-3 text-xs font-bold" aria-label="Cambiar idioma">{lang==="es"?"EN":"ES"}</button>
          <Button onClick={()=>openBooking()} className="hidden h-11 rounded-none px-6 text-xs font-black tracking-[.12em] sm:flex">{t("RESERVAR","BOOK NOW")} <ArrowRight/></Button>
          <button onClick={()=>setMenuOpen(!menuOpen)} className="grid h-10 w-10 place-items-center lg:hidden" aria-label="Menú">{menuOpen?<X/>:<Menu/>}</button>
        </div>
      </div>
      {menuOpen&&<nav className="border-t border-white/10 bg-[#10100e] p-5 lg:hidden">{[["#servicios",t("Servicios","Services")],["#barberos",t("Barberos","Barbers")],["#trabajo",t("Cortes","Cuts")],["#vip","VIP"],["#estudio",t("El estudio","Studio")]].map(([h,l])=><a onClick={()=>setMenuOpen(false)} className="block border-b border-white/10 py-4 text-xl font-bold" key={h} href={h}>{l}</a>)}</nav>}
    </header>

    <section id="inicio" className="grain relative min-h-[860px] pt-[72px] lg:h-screen lg:min-h-[720px]">
      <SilentVideo {...studioMedia.hero} className="absolute inset-0 opacity-70 lg:left-[38%]"/>
      <div className="absolute inset-0 bg-[linear-gradient(90deg,#090908_0%,rgba(9,9,8,.88)_40%,rgba(9,9,8,.16)_78%),linear-gradient(0deg,#090908_0%,transparent_45%)]"/>
      <div className="relative z-10 mx-auto grid h-full max-w-[1500px] content-center gap-10 px-5 py-16 lg:grid-cols-[1.15fr_.65fr] lg:px-10">
        <div className="rise max-w-4xl pt-10 lg:pt-0">
          <div className="eyebrow mb-6 flex items-center gap-3 text-[#e84c3d]"><span className="h-px w-10 bg-[#e84c3d]"/>DESDE 2021 · BOCAGRANDE · CARTAGENA</div>
          <h1 className="display text-[clamp(5rem,11vw,10.5rem)] leading-[.76]">Jota<br/><span className="text-[#e84c3d]">Eme.</span></h1>
          <p className="mt-8 max-w-xl text-xl font-medium leading-relaxed text-white/78 sm:text-2xl">{t("Más que un corte. Una experiencia diseñada para ti.","More than a haircut. An experience designed for you.")}</p>
          <div className="mt-9 flex flex-wrap gap-3"><Button onClick={()=>openBooking()} className="h-14 rounded-none px-8 text-sm font-black tracking-[.12em]">{t("RESERVAR CITA","BOOK APPOINTMENT")} <ArrowRight/></Button><a href="#servicios" className="flex h-14 items-center border border-white/25 px-7 text-sm font-bold hover:border-white">{t("VER SERVICIOS","VIEW SERVICES")}</a></div>
          <div className="mt-10 flex gap-8 text-sm text-white/60"><span className="flex items-center gap-2"><Clock3 size={17}/>{t("Lun—Sáb","Mon—Sat")} · 9:15—20:20</span><span className="hidden items-center gap-2 sm:flex"><MapPin size={17}/>Av. San Martín · Local 7</span></div>
        </div>
        <div className="self-end lg:self-center">
          <div className="border border-white/15 bg-[#10100e]/90 p-5 shadow-2xl backdrop-blur-xl sm:p-7">
            <div className="mb-6 flex items-start justify-between"><div><p className="eyebrow text-[#e84c3d]">{t("PRÓXIMOS ESPACIOS","NEXT OPENINGS")}</p><h2 className="mt-2 text-2xl font-bold">{t("Hoy en Jota Eme","Today at Jota Eme")}</h2></div><CalendarDays className="text-white/35"/></div>
            <div className="grid grid-cols-3 gap-2">{slots.slice(3).map((slot,i)=><button key={slot} onClick={()=>openBooking(i===2?"premium":"haircut")} className="border border-white/12 bg-white/[.04] px-2 py-4 text-sm font-bold transition hover:border-[#e84c3d] hover:bg-[#e84c3d] hover:text-black">{slot}</button>)}</div>
            <p className="mt-5 text-xs leading-relaxed text-white/45">{t("Selecciona el servicio y tu barbero. Confirmas en menos de un minuto.","Choose your service and barber. Confirm in under a minute.")}</p>
          </div>
        </div>
      </div>
    </section>

    <div className="overflow-hidden border-y border-white/10 bg-[#e84c3d] py-3 text-black"><div className="marquee-track flex w-max whitespace-nowrap text-sm font-black tracking-[.16em]"><span className="px-6">CORTES · BARBA · FACIAL · COLOR · VIP · DOMICILIOS · </span><span className="px-6">CORTES · BARBA · FACIAL · COLOR · VIP · DOMICILIOS · </span><span className="px-6">CORTES · BARBA · FACIAL · COLOR · VIP · DOMICILIOS · </span><span className="px-6">CORTES · BARBA · FACIAL · COLOR · VIP · DOMICILIOS · </span></div></div>

    <section id="servicios" className="mx-auto max-w-[1500px] px-5 py-24 lg:px-10 lg:py-36">
      <div className="mb-12 grid gap-6 lg:grid-cols-2"><div><p className="eyebrow text-[#e84c3d]">01 · {t("SERVICIOS","SERVICES")}</p><h2 className="display mt-3 text-6xl leading-none sm:text-8xl">{t("Elige tu nivel.","Choose your level.")}</h2></div><p className="max-w-lg self-end text-lg leading-relaxed text-white/55">{t("Cuidado preciso, atención sin prisa y cada detalle pensado para que salgas impecable.","Precise grooming, unrushed attention and every detail considered so you leave looking sharp.")}</p></div>
      <div className="grid border-l border-t border-white/15 sm:grid-cols-2 lg:grid-cols-4">{services.filter(s=>s.featured).map((s,i)=><article key={s.id} className="group relative min-h-[310px] border-b border-r border-white/15 p-6 transition hover:bg-[#e84c3d] hover:text-black"><span className="text-xs font-bold opacity-40">0{i+1}</span><Scissors className="absolute right-6 top-6 opacity-30"/><h3 className="mt-16 text-3xl font-black leading-tight">{lang==="es"?s.es:s.en}</h3><p className="mt-3 text-sm opacity-55">{s.includes.slice(0,2).join(" · ")}</p><div className="absolute inset-x-6 bottom-6 flex items-end justify-between"><div><b className="text-xl">{money(s.price)}</b><span className="mt-1 block text-xs opacity-50">{s.minutes} min</span></div><button onClick={()=>openBooking(s.id)} className="grid h-12 w-12 place-items-center border border-current" aria-label={`Reservar ${s.es}`}><ArrowRight/></button></div></article>)}</div>
      <div className="mt-7 flex justify-end"><Link href="/services" className="flex items-center gap-3 text-sm font-black tracking-[.12em] text-[#e84c3d]">{t("VER LOS 14 SERVICIOS","VIEW ALL 14 SERVICES")} <ArrowRight/></Link></div>
    </section>

    <section id="barberos" className="bg-[#f3f0e8] px-5 py-24 text-black lg:px-10 lg:py-36">
      <div className="mx-auto max-w-[1500px]"><p className="eyebrow">02 · {t("TU BARBERO","YOUR BARBER")}</p><div className="mt-4 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="display max-w-4xl text-6xl leading-[.9] sm:text-8xl">{t("Dos estilos. Un estándar.","Two styles. One standard.")}</h2><p className="max-w-sm text-black/55">{t("Elige con quién quieres reservar o selecciona máxima disponibilidad.","Choose who you want to book with, or select maximum availability.")}</p></div>
        <div className="mt-14 grid gap-5 lg:grid-cols-2">{barbers.map((b,i)=><article key={b.id} className="group grid min-h-[480px] overflow-hidden bg-[#11110f] text-white sm:grid-cols-[1.1fr_.9fr]"><img src={b.image} alt={b.name} className="h-80 w-full object-cover object-top grayscale transition duration-700 group-hover:grayscale-0 sm:h-full"/><div className="flex flex-col justify-between p-7"><span className="display text-7xl text-[#e84c3d]">0{i+1}</span><div><h3 className="display text-5xl leading-none">{b.name}</h3><p className="mt-3 text-sm text-white/50">{b.specialties}</p><p className="mt-8 flex items-center gap-2 text-sm"><Instagram size={17}/>{b.handle}</p><Button onClick={()=>{setSelectedService("haircut");setBookingOpen(true)}} className="mt-6 h-12 w-full rounded-none">{t("RESERVAR CON ","BOOK WITH ")}{b.name.split(" ")[0].toUpperCase()} <ArrowRight/></Button></div></div></article>)}</div>
      </div>
    </section>

    <section id="trabajo" className="border-b border-white/10 px-5 py-24 lg:px-10 lg:py-36">
      <div className="mx-auto max-w-[1500px]">
        <div className="grid gap-6 lg:grid-cols-[1.05fr_.75fr] lg:items-end"><div><p className="eyebrow text-[#e84c3d]">03 · {t("NUESTRO TRABAJO","OUR WORK")}</p><h2 className="display mt-4 text-6xl leading-[.88] sm:text-9xl">{t("CORTES QUE HABLAN.","CUTS THAT SPEAK.")}</h2></div><p className="max-w-xl text-lg leading-relaxed text-white/55">{t("Trabajo real de Jota Eme y Cheo. Fades limpios, textura, barba y transformaciones hechas en Cartagena.","Real work by Jota Eme and Cheo. Clean fades, texture, beard work and transformations made in Cartagena.")}</p></div>
        <div className="mt-14 grid gap-4 md:grid-cols-3">{portfolio.map((look,index)=><article key={look.image} className={`group relative overflow-hidden bg-[#171715] ${index===1?"md:translate-y-10":""}`}>{look.video?<SilentVideo src={look.video} poster={look.poster??look.image} className="relative aspect-[4/5] w-full"/>:<img src={look.image} alt={t(look.es,look.en)} loading="lazy" width={720} height={1280} className="aspect-[4/5] w-full object-cover transition duration-700 group-hover:scale-[1.035]"/>}<div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5"><h3 className="text-2xl font-black">{t(look.es,look.en)}</h3><p className="mt-1 text-sm text-white/65">{t(look.detailEs,look.detailEn)}</p><button onClick={()=>openBooking(look.service)} className="mt-4 inline-flex items-center gap-2 border-b border-white/40 pb-1 text-xs font-bold tracking-widest">{t("RESERVAR ESTE LOOK","BOOK THIS LOOK")} <ArrowRight size={15}/></button></div></article>)}</div>
        <div className="mt-24 grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="eyebrow text-[#e84c3d]">JOTA EME · {t("EN MOVIMIENTO","IN MOTION")}</p><h3 className="display mt-4 text-5xl leading-none sm:text-7xl">{t("EL DETALLE LO ES TODO.","IT’S ALL IN THE DETAIL.")}</h3><p className="mt-5 max-w-md text-white/55">{t("Las manos, la técnica y el resultado. Así se vive una sesión en Jota Eme.","The hands, the technique and the result. A glimpse into a session at Jota Eme.")}</p><Button onClick={()=>openBooking()} className="mt-7 h-12 rounded-none px-6">{t("RESERVA TU SESIÓN","BOOK YOUR SESSION")} <ArrowRight size={17}/></Button></div><div className="grid grid-cols-2 gap-3 sm:gap-5"><SilentVideo {...studioMedia.cut} className="relative aspect-[9/16] bg-[#171715]"/><SilentVideo {...studioMedia.ritual} className="relative aspect-[9/16] translate-y-8 bg-[#171715] sm:translate-y-12"/></div></div>
      </div>
    </section>

    <section id="vip" className="grain relative overflow-hidden border-b border-white/10 bg-[#141411] px-5 py-24 lg:px-10 lg:py-36"><div className="studio-grid absolute inset-0 opacity-40"/><div className="relative mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="eyebrow text-[#e84c3d]">04 · VIP JOTA EME</p><h2 className="display mt-5 text-[clamp(4.5rem,9vw,9rem)] leading-[.8]">NO ES<br/>UN CORTE.<br/><span className="text-[#e84c3d]">ES EL RITUAL.</span></h2></div><div className="border border-white/15 bg-black/30 p-7 sm:p-10"><Sparkles className="mb-8 text-[#e84c3d]" size={35}/><p className="text-2xl font-medium leading-relaxed">{t("Una sesión completa de 90 minutos para quien quiere la experiencia Jota Eme sin recortar detalles.","A complete 90-minute session for those who want the full Jota Eme experience without cutting corners.")}</p><div className="my-8 space-y-4 border-y border-white/15 py-7">{[t("Consulta de estilo","Style consultation"),t("Corte y ritual de barba","Haircut and beard ritual"),t("Cuidado facial y acabado","Facial care and finishing"),t("Atención y bebida de cortesía","Premium service and drink")].map(x=><p key={x} className="flex items-center gap-3 text-white/70"><Check size={17} className="text-[#e84c3d]"/>{x}</p>)}</div><div className="flex items-center justify-between"><div><b className="text-3xl">$160.000</b><small className="block text-white/40">90 MIN</small></div><Button onClick={()=>openBooking("vip")} className="h-13 rounded-none px-6">{t("RESERVAR VIP","BOOK VIP")} <ArrowRight/></Button></div></div></div></section>

    <section className="mx-auto grid max-w-[1500px] gap-10 px-5 py-24 lg:grid-cols-2 lg:px-10 lg:py-36"><div className="relative min-h-[500px] overflow-hidden bg-[#20201c]"><img src="/look-house-call.jpg" alt="Servicio de barbería Jota Eme a domicilio" className="h-full w-full object-cover opacity-75"/><span className="display absolute bottom-6 left-6 text-7xl text-[#e84c3d]">WE COME<br/>TO YOU.</span></div><div className="self-center"><p className="eyebrow text-[#e84c3d]">05 · {t("DOMICILIOS","HOUSE CALLS")}</p><h2 className="display mt-4 text-6xl leading-none sm:text-8xl">{t("Tu lugar. Nuestro estándar.","Your place. Our standard.")}</h2><p className="mt-7 max-w-xl text-lg leading-relaxed text-white/55">{t("Servicio completo en hoteles, villas y residencias. Ideal para bodas, artistas, ejecutivos y grupos que quieren prepararse juntos.","Full service at hotels, villas and residences. Ideal for weddings, artists, executives and groups getting ready together.")}</p><div className="mt-8 flex items-center gap-8"><div><b className="text-2xl">$200.000</b><small className="block text-white/40">{t("DESDE 120 MIN","FROM 120 MIN")}</small></div><Button onClick={()=>openBooking("house")} className="h-13 rounded-none px-7">{t("SOLICITAR","REQUEST")} <ArrowRight/></Button></div></div></section>

    <section id="estudio" className="border-y border-white/10 bg-[#e84c3d] px-5 py-24 text-black lg:px-10"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow">06 · {t("ENCUÉNTRANOS","FIND US")}</p><h2 className="display mt-4 text-6xl leading-[.9] sm:text-9xl">BOCAGRANDE.<br/>LOCAL 7.</h2><p className="mt-8 max-w-xl text-xl font-medium">Av. San Martín · Edificio San Martín<br/>Cartagena, Colombia</p></div><div className="border border-black/25 p-7"><div className="flex justify-between border-b border-black/20 pb-5"><b>{t("Lunes — Sábado","Monday — Saturday")}</b><span>9:15 — 20:20</span></div><div className="flex justify-between border-b border-black/20 py-5"><b>{t("Domingo","Sunday")}</b><span>{t("Cerrado","Closed")}</span></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><a target="_blank" rel="noreferrer" href="https://maps.google.com/?q=Av.+San+Martín+Edificio+San+Martín+Local+7+Cartagena" className="flex h-13 items-center justify-center gap-2 bg-black px-5 text-sm font-bold text-white"><MapPin/> {t("CÓMO LLEGAR","DIRECTIONS")}</a><a href="https://wa.me/573214692733" className="flex h-13 items-center justify-center gap-2 border border-black px-5 text-sm font-bold"><Phone/> WHATSAPP</a></div></div></div></section>

    <section className="px-5 py-28 text-center lg:px-10 lg:py-40"><p className="eyebrow text-[#e84c3d]">{t("TU PRÓXIMO CORTE","YOUR NEXT CUT")}</p><h2 className="display mx-auto mt-5 max-w-6xl text-[clamp(4rem,10vw,10rem)] leading-[.8]">{t("EMPIEZA AQUÍ.","STARTS HERE.")}</h2><Button onClick={()=>openBooking()} className="mt-10 h-16 rounded-none px-10 text-sm font-black tracking-[.12em]">{t("RESERVAR AHORA","BOOK NOW")} <ArrowRight/></Button></section>
    <footer className="border-t border-white/10 px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-[1500px] flex-col gap-5 text-sm text-white/45 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><img src="/jota-eme-logo.jpg" alt="Jota Eme Barber Studio" className="h-12 w-12 rounded-full bg-white object-cover"/><b className="display text-2xl text-white">JOTA EME.</b></div><span>© 2026 Jota Eme Barber Studio</span><div className="flex gap-5"><a href="https://www.instagram.com/jotaemebarberstudio">Instagram</a><a href="/admin">Admin</a><a href="https://book.weibook.co/jotaeme-barberstudio">WeiBook</a></div></div></footer>

    <div className="fixed inset-x-0 bottom-0 z-30 flex border-t border-white/15 bg-[#0b0b0a]/95 p-3 backdrop-blur-xl sm:hidden"><Button onClick={()=>openBooking()} className="h-13 w-full rounded-none text-sm font-black tracking-[.1em]">{t("RESERVAR CITA","BOOK APPOINTMENT")} <ArrowRight/></Button></div>
    <BookingDialog key={`${bookingOpen}-${selectedService}`} open={bookingOpen} onOpenChange={setBookingOpen} initialService={selectedService} lang={lang}/>
  </main>;
}

function BookingDialog({open,onOpenChange,initialService,lang}:{open:boolean;onOpenChange:(v:boolean)=>void;initialService:string;lang:"es"|"en"}){
  const [step,setStep]=useState(1);const [serviceId,setServiceId]=useState(initialService);const [barber,setBarber]=useState("any");const [day,setDay]=useState(0);const [slot,setSlot]=useState("");const [submitted,setSubmitted]=useState(false);const [loading,setLoading]=useState(false);const [form,setForm]=useState({name:"",phone:"",email:"",notes:""});
  const t=(es:string,en:string)=>lang==="es"?es:en;const service=services.find(s=>s.id===serviceId)!;
  const days=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d}),[]);
  const submit=async()=>{if(!form.name||!form.phone||!slot)return;setLoading(true);try{const response=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId,barber,date:days[day].toISOString().slice(0,10),time:slot,...form})});const data=await response.json();if(!response.ok){window.alert(data.error??t("No pudimos confirmar la cita.","We couldn’t confirm the booking."));return}setBarber(data.barberId??barber);setSubmitted(true)}catch{window.alert(t("Revisa tu conexión e intenta de nuevo.","Check your connection and try again."))}finally{setLoading(false)}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto border-white/15 bg-[#11110f] p-0 text-white sm:max-w-3xl"><DialogHeader className="border-b border-white/10 p-5 pr-14 text-left"><DialogTitle className="display text-3xl">{submitted?t("CITA CONFIRMADA","BOOKING CONFIRMED"):t("RESERVA TU CITA","BOOK YOUR APPOINTMENT")}</DialogTitle><DialogDescription className="text-white/45">{submitted?t("Nos vemos pronto en Jota Eme.","See you soon at Jota Eme."):t(`Paso ${step} de 4`,`Step ${step} of 4`)}</DialogDescription></DialogHeader>
    {submitted?<div className="p-7 text-center sm:p-12"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#e84c3d] text-black"><Check size={38}/></div><h3 className="mt-6 text-3xl font-black">{form.name}, {t("estás listo.","you’re all set.")}</h3><p className="mt-3 text-white/55">{lang==="es"?service.es:service.en} · {slots.includes(slot)?slot:""}<br/>{barber==="any"?t("Primer barbero disponible","First available barber"):barbers.find(b=>b.id===barber)?.name}</p><div className="mx-auto mt-7 max-w-md border border-white/15 p-5 text-left text-sm text-white/60"><b className="mb-2 block text-white">{t("Confirmación por WhatsApp","WhatsApp confirmation")}</b>{t("Te enviaremos los detalles y recordatorios al número que registraste.","We’ll send details and reminders to the number you provided.")}</div><Button onClick={()=>onOpenChange(false)} className="mt-7 h-12 rounded-none px-7">{t("LISTO","DONE")}</Button></div>:<>
      <div className="flex gap-1 px-5 pt-5">{[1,2,3,4].map(n=><span key={n} className={`h-1 flex-1 ${n<=step?"bg-[#e84c3d]":"bg-white/10"}`}/>)}</div>
      <div className="p-5 sm:p-7">
        {step===1&&<div><p className="eyebrow mb-4 text-white/45">{t("ELIGE SERVICIO","CHOOSE A SERVICE")}</p><div className="grid max-h-[440px] gap-2 overflow-y-auto sm:grid-cols-2">{services.map(s=><button key={s.id} onClick={()=>{setServiceId(s.id);setStep(2)}} className={`flex min-h-20 items-center justify-between border p-4 text-left transition ${serviceId===s.id?"border-[#e84c3d] bg-[#e84c3d]/10":"border-white/10 hover:border-white/35"}`}><div><b>{lang==="es"?s.es:s.en}</b><small className="mt-1 block text-white/40">{s.minutes} min</small></div><b className="ml-3 text-[#e84c3d]">{money(s.price)}</b></button>)}</div></div>}
        {step===2&&<div><p className="eyebrow mb-4 text-white/45">{t("ELIGE BARBERO","CHOOSE A BARBER")}</p><button onClick={()=>{setBarber("any");setStep(3)}} className="mb-3 flex w-full items-center gap-4 border border-[#e84c3d] bg-[#e84c3d]/10 p-4 text-left"><div className="grid h-14 w-14 place-items-center bg-[#e84c3d] text-black"><Sparkles/></div><div><b>{t("Máxima disponibilidad","Maximum availability")}</b><small className="mt-1 block text-white/45">{t("El primer barbero disponible","First available barber")}</small></div></button><div className="grid gap-3 sm:grid-cols-2">{barbers.map(b=><button key={b.id} onClick={()=>{setBarber(b.id);setStep(3)}} className="flex items-center gap-4 border border-white/10 p-4 text-left hover:border-white/40"><img src={b.image} alt="" className="h-16 w-16 object-cover object-top grayscale"/><div><b>{b.name}</b><small className="mt-1 block text-white/45">{b.specialties}</small></div></button>)}</div></div>}
        {step===3&&<div><p className="eyebrow mb-4 text-white/45">{t("ELIGE FECHA Y HORA","CHOOSE DATE & TIME")}</p><div className="hide-scrollbar flex gap-2 overflow-x-auto pb-3">{days.map((d,i)=><button key={i} onClick={()=>setDay(i)} className={`min-w-20 border px-3 py-3 text-center ${day===i?"border-[#e84c3d] bg-[#e84c3d] text-black":"border-white/10"}`}><small className="block text-[10px] font-bold uppercase">{i===0?t("HOY","TODAY"):d.toLocaleDateString(lang==="es"?"es-CO":"en-US",{weekday:"short"})}</small><b className="mt-1 block text-xl">{d.getDate()}</b></button>)}</div><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map(s=><button key={s} onClick={()=>setSlot(s)} className={`border px-2 py-4 text-sm font-bold ${slot===s?"border-[#e84c3d] bg-[#e84c3d] text-black":"border-white/10 hover:border-white/40"}`}>{s}</button>)}</div><Button disabled={!slot} onClick={()=>setStep(4)} className="mt-6 h-12 w-full rounded-none">{t("CONTINUAR","CONTINUE")} <ArrowRight/></Button></div>}
        {step===4&&<div><p className="eyebrow mb-4 text-white/45">{t("TUS DATOS","YOUR DETAILS")}</p><div className="mb-5 border border-white/10 bg-white/[.03] p-4"><div className="flex justify-between"><b>{lang==="es"?service.es:service.en}</b><b className="text-[#e84c3d]">{money(service.price)}</b></div><small className="mt-2 block text-white/45">{days[day].toLocaleDateString(lang==="es"?"es-CO":"en-US",{weekday:"long",month:"long",day:"numeric"})} · {slot}</small></div><div className="grid gap-3 sm:grid-cols-2"><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={t("Nombre completo","Full name")} className="h-12 rounded-none border-white/15 bg-white/[.04]"/><Input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="WhatsApp" className="h-12 rounded-none border-white/15 bg-white/[.04]"/><Input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email (opcional)" className="h-12 rounded-none border-white/15 bg-white/[.04] sm:col-span-2"/><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder={t("Notas para tu barbero (opcional)","Notes for your barber (optional)")} className="min-h-24 rounded-none border-white/15 bg-white/[.04] sm:col-span-2"/></div><Button disabled={!form.name||!form.phone||loading} onClick={submit} className="mt-5 h-13 w-full rounded-none font-black">{loading?t("CONFIRMANDO...","CONFIRMING..."):t("CONFIRMAR CITA","CONFIRM APPOINTMENT")} <Check/></Button></div>}
      </div>
      {step>1&&<div className="border-t border-white/10 p-4"><button onClick={()=>setStep(step-1)} className="flex items-center gap-2 text-sm text-white/55 hover:text-white"><ChevronLeft size={17}/>{t("Atrás","Back")}</button></div>}
    </>}
  </DialogContent></Dialog>;
}
